version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.8

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: pip install requests

      - run:
          name: Execute Python script
          command: python3 snmp_exporter.py
