version: 2.1
jobs:
  build:
    docker:
      - image: ubuntu:22.04

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Install Python
          command: |
            apt-get update
            apt-get install -y python3 python3-pip

      - run:
          name: Install dependencies
          command: pip3 install requests

      - run:
          name: Execute Python script
          command: python3 snmp_exporter.py

      - run:
          name: Check status of snmp-exporter service
          command: |
            systemctl status snmp-exporter.service

workflows:
  version: 2
  build:
    jobs:
      - build
